services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
  proxy:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web
      - server
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/temp-build
      - /app/web
