services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
  proxy:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web
      - server
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/
    volumes:
      - ./:/app
      - /app/temp-build
      - /app/web
    depends_on:
      - mongo
  mongo:
    image: mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
