services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
  proxy:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web
      - server
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/
      REDIS_URI: redis://redis:6379/0
    volumes:
      - ./:/app
      - /app/temp-build
      - /app/web
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    depends_on:
      - server
      - mongo
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  redis:
    image: redis:alpine
